In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\ABINAYA\Downloads\predictive_maintenance.csv")

In [3]:
df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Target,Failure Type
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,No Failure
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,No Failure
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,No Failure
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,No Failure
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,No Failure

In [ ]:
df['rolling_air_temp_win=3']=df['Air temperature [K]'].rolling(window=3).mean()

In [ ]:
df.head(15)

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Target,Failure Type,rolling_air_temp_win=3
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,No Failure,NaN
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,No Failure,NaN
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,No Failure,298.133333
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,No Failure,298.166667
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,No Failure,298.166667
5,6,M14865,M,298.1,308.6,1425,41.9,11,0,No Failure,298.166667
6,7,L47186,L,298.1,308.6,1558,42.4,14,0,No Failure,298.133333
7,8,L47187,L,298.1,308.6,1527,40.2,16,0,No Failure,298.100000
8,9,M14868,M,298.3,308.7,1667,28.6,18,0,No Failure,298.166667
9,10,M14869,M,298.5,309.0,1741,28.0,21,0,No Failure,298.300000
10,11,H29424,H,298.4,308.9,1782,23.9,24,0,No Failure,298.400000
11,12,H29425,H,298.6,309.1,1423,44.3,29,0,No Failure,298.500000
12,13,M14872,M,298.6,309.1,1339,51.1,34,0,No Failure,298.533333
13,14,M14873,M,298.6,309.2,1742,30.0,37,0,No Failure,298.600000
14,15,L47194,L,298.6,309.2,2035,19.6,40,0,No Failure,298.600000

In [6]:
df['rolling_air_temp_win5']=df['Air temperature [K]'].rolling(window=5).mean()
df.head(15)

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Target,Failure Type,rolling_air_temp_win=3,rolling_air_temp_win5
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,No Failure,NaN,NaN
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,No Failure,NaN,NaN
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,No Failure,298.133333,NaN
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,No Failure,298.166667,NaN
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,No Failure,298.166667,298.16
5,6,M14865,M,298.1,308.6,1425,41.9,11,0,No Failure,298.166667,298.16
6,7,L47186,L,298.1,308.6,1558,42.4,14,0,No Failure,298.133333,298.14
7,8,L47187,L,298.1,308.6,1527,40.2,16,0,No Failure,298.100000,298.14
8,9,M14868,M,298.3,308.7,1667,28.6,18,0,No Failure,298.166667,298.16
9,10,M14869,M,298.5,309.0,1741,28.0,21,0,No Failure,298.300000,298.22
10,11,H29424,H,298.4,308.9,1782,23.9,24,0,No Failure,298.400000,298.28
11,12,H29425,H,298.6,309.1,1423,44.3,29,0,No Failure,298.500000,298.38
12,13,M14872,M,298.6,309.1,1339,51.1,34,0,No Failure,298.533333,298.48
13,14,M14873,M,298.6,309.2,1742,30.0,37,0,No Failure,298.600000,298.54
14,15,L47194,L,298.6,309.2,2035,19.6,40,0,No Failure,298.600000,298.56

In [7]:
df['rolling_air_temp_variance_win3']=df['Air temperature [K]'].rolling(window=3).var()
df.head(15)

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Target,Failure Type,rolling_air_temp_win=3,rolling_air_temp_win5,rolling_air_temp_variance_win3
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,No Failure,NaN,NaN,NaN
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,No Failure,NaN,NaN,NaN
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,No Failure,298.133333,NaN,0.003333
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,No Failure,298.166667,NaN,0.003333
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,No Failure,298.166667,298.16,0.003333
5,6,M14865,M,298.1,308.6,1425,41.9,11,0,No Failure,298.166667,298.16,0.003333
6,7,L47186,L,298.1,308.6,1558,42.4,14,0,No Failure,298.133333,298.14,0.003333
7,8,L47187,L,298.1,308.6,1527,40.2,16,0,No Failure,298.100000,298.14,0.000000
8,9,M14868,M,298.3,308.7,1667,28.6,18,0,No Failure,298.166667,298.16,0.013333
9,10,M14869,M,298.5,309.0,1741,28.0,21,0,No Failure,298.300000,298.22,0.040000
10,11,H29424,H,298.4,308.9,1782,23.9,24,0,No Failure,298.400000,298.28,0.010000
11,12,H29425,H,298.6,309.1,1423,44.3,29,0,No Failure,298.500000,298.38,0.010000
12,13,M14872,M,298.6,309.1,1339,51.1,34,0,No Failure,298.533333,298.48,0.013333
13,14,M14873,M,298.6,309.2,1742,30.0,37,0,No Failure,298.600000,298.54,0.000000
14,15,L47194,L,298.6,309.2,2035,19.6,40,0,No Failure,298.600000,298.56,0.000000

In [8]:
df['rolling_air_temp_variance_win5']=df['Air temperature [K]'].rolling(window=5).var()
df.head(15)

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Target,Failure Type,rolling_air_temp_win=3,rolling_air_temp_win5,rolling_air_temp_variance_win3,rolling_air_temp_variance_win5
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,No Failure,NaN,NaN,NaN,NaN
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,No Failure,NaN,NaN,NaN,NaN
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,No Failure,298.133333,NaN,0.003333,NaN
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,No Failure,298.166667,NaN,0.003333,NaN
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,No Failure,298.166667,298.16,0.003333,0.003
5,6,M14865,M,298.1,308.6,1425,41.9,11,0,No Failure,298.166667,298.16,0.003333,0.003
6,7,L47186,L,298.1,308.6,1558,42.4,14,0,No Failure,298.133333,298.14,0.003333,0.003
7,8,L47187,L,298.1,308.6,1527,40.2,16,0,No Failure,298.100000,298.14,0.000000,0.003
8,9,M14868,M,298.3,308.7,1667,28.6,18,0,No Failure,298.166667,298.16,0.013333,0.008
9,10,M14869,M,298.5,309.0,1741,28.0,21,0,No Failure,298.300000,298.22,0.040000,0.032
10,11,H29424,H,298.4,308.9,1782,23.9,24,0,No Failure,298.400000,298.28,0.010000,0.032
11,12,H29425,H,298.6,309.1,1423,44.3,29,0,No Failure,298.500000,298.38,0.010000,0.037
12,13,M14872,M,298.6,309.1,1339,51.1,34,0,No Failure,298.533333,298.48,0.013333,0.017
13,14,M14873,M,298.6,309.2,1742,30.0,37,0,No Failure,298.600000,298.54,0.000000,0.008
14,15,L47194,L,298.6,309.2,2035,19.6,40,0,No Failure,298.600000,298.56,0.000000,0.008