##Day 1

In [34]:
import pandas as pd
import matplotlib.pyplot as plt

In [35]:
df=pd.read_csv(r"C:\Users\ABINAYA\Downloads\predictive_maintenance.csv")

In [36]:
df.shape

(10000, 10)

In [37]:
df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Target,Failure Type
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,No Failure
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,No Failure
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,No Failure
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,No Failure
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,No Failure

In [38]:
df["timestamp"] = pd.date_range(start="2025-01-01 00:00:00",periods=len(df),freq="h")

In [39]:
df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Target,Failure Type,timestamp
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,No Failure,2025-01-01 00:00:00
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,No Failure,2025-01-01 01:00:00
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,No Failure,2025-01-01 02:00:00
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,No Failure,2025-01-01 03:00:00
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,No Failure,2025-01-01 04:00:00

In [40]:
columns= ['timestamp'] + [col for col in df.columns if col != 'timestamp']

In [41]:
df = df[columns]

In [42]:
df.head()

,timestamp,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Target,Failure Type
0,2025-01-01 00:00:00,1,M14860,M,298.1,308.6,1551,42.8,0,0,No Failure
1,2025-01-01 01:00:00,2,L47181,L,298.2,308.7,1408,46.3,3,0,No Failure
2,2025-01-01 02:00:00,3,L47182,L,298.1,308.5,1498,49.4,5,0,No Failure
3,2025-01-01 03:00:00,4,L47183,L,298.2,308.6,1433,39.5,7,0,No Failure
4,2025-01-01 04:00:00,5,L47184,L,298.2,308.7,1408,40.0,9,0,No Failure

In [43]:
print("Duplicate timestamps:",df["timestamp"].duplicated().sum())

Duplicate timestamps: 0

In [44]:
print(df['timestamp'].isnull().sum())

0

In [45]:
is_sorted = df["timestamp"].is_monotonic_increasing
print(is_sorted)

True

In [46]:
df.to_csv("predictive_maintainence_timestamp.csv",index=False)